<a href="https://colab.research.google.com/github/kushv16/Audio-Sentiment-Analysis/blob/master/Crema_Feature_Merging.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [43]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive

In [44]:
!pip install noisereduce

import pandas as pd
import numpy as np
import random
from glob import glob
import os
import librosa
import noisereduce as nr

import warnings
warnings.filterwarnings("ignore")

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: noisereduce in /usr/local/lib/python3.8/dist-packages (2.0.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.8/dist-packages (from noisereduce) (1.22.4)
Requirement already satisfied: scipy in /usr/local/lib/python3.8/dist-packages (from noisereduce) (1.7.3)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.8/dist-packages (from noisereduce) (3.5.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.8/dist-packages (from noisereduce) (4.64.1)
Requirement already satisfied: librosa in /usr/local/lib/python3.8/dist-packages (from noisereduce) (0.8.1)
Requirement already satisfied: audioread>=2.0.0 in /usr/local/lib/python3.8/dist-packages (from librosa->noisereduce) (3.0.0)
Requirement already satisfied: decorator>=3.0.0 in /usr/local/lib/python3.8/dist-packages (from librosa->noisereduce) (4.4.2)
Requirement already satisfied: scikit-learn!=0.19.0,>=0.14.0 in /usr/local/lib/python3.8/dist-packages (from librosa->noisereduce) (1.0.2)
Requirement already satisfied: numba>=0.43.0 in /usr/local/lib/python3.8/dist-packages (from librosa->noisereduce) (0.56.4)
Requirement already satisfied: soundfile>=0.10.2 in /usr/local/lib/python3.8/dist-packages (from librosa->noisereduce) (0.12.1)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.8/dist-packages (from librosa->noisereduce) (23.0)
Requirement already satisfied: joblib>=0.14 in /usr/local/lib/python3.8/dist-packages (from librosa->noisereduce) (1.2.0)
Requirement already satisfied: resampy>=0.2.2 in /usr/local/lib/python3.8/dist-packages (from librosa->noisereduce) (0.4.2)
Requirement already satisfied: pooch>=1.0 in /usr/local/lib/python3.8/dist-packages (from librosa->noisereduce) (1.6.0)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.8/dist-packages (from matplotlib->noisereduce) (2.8.2)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.8/dist-packages (from matplotlib->noisereduce) (1.4.4)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.8/dist-packages (from matplotlib->noisereduce) (4.38.0)
Requirement already satisfied: pyparsing>=2.2.1 in /usr/local/lib/python3.8/dist-packages (from matplotlib->noisereduce) (3.0.9)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.8/dist-packages (from matplotlib->noisereduce) (0.11.0)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.8/dist-packages (from matplotlib->noisereduce) (7.1.2)
Requirement already satisfied: setuptools in /usr/local/lib/python3.8/dist-packages (from numba>=0.43.0->librosa->noisereduce) (57.4.0)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.8/dist-packages (from numba>=0.43.0->librosa->noisereduce) (6.0.0)
Requirement already satisfied: llvmlite<0.40,>=0.39.0dev0 in /usr/local/lib/python3.8/dist-packages (from numba>=0.43.0->librosa->noisereduce) (0.39.1)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.8/dist-packages (from pooch>=1.0->librosa->noisereduce) (2.25.1)
Requirement already satisfied: appdirs>=1.3.0 in /usr/local/lib/python3.8/dist-packages (from pooch>=1.0->librosa->noisereduce) (1.4.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.7->matplotlib->noisereduce) (1.15.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.8/dist-packages (from scikit-learn!=0.19.0,>=0.14.0->librosa->noisereduce) (3.1.0)
Requirement already satisfied: cffi>=1.0 in /usr/local/lib/python3.8/dist-packages (from soundfile>=0.10.2->librosa->noisereduce) (1.15.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.8/dist-packages (from cffi>=1.0->soundfile>=0.10.2->librosa->noisereduce) (2.21)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.8/dist-packages (from requests>=2.19.0->pooch>=1.0->librosa->noisereduce) (1.24.3)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.8/dist-packages (from requests>=2.19.0->pooch>=1.0->librosa->noisereduce) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/dist-packages (from requests>=2.19.0->pooch>=1.0->librosa->noisereduce) (2022.12.7)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/local/lib/python3.8/dist-packages (from requests>=2.19.0->pooch>=1.0->librosa->noisereduce) (4.0.0)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.8/dist-packages (from importlib-metadata->numba>=0.43.0->librosa->noisereduce) (3.14.0)

In [45]:
df_fund = pd.read_csv('/content/drive/MyDrive/LY Project/Dataframes/Features/Crema-D/crema_fundamental_frequency.csv',index_col=0)
df_misc = pd.read_csv('/content/drive/MyDrive/LY Project/Dataframes/Features/Crema-D/crema_chroma_features.csv', index_col=0)
df_mfcc = pd.read_csv('/content/drive/MyDrive/LY Project/Dataframes/Features/Crema-D/crema_mfcc.csv', index_col=0)

df_fund.shape, df_misc.shape, df_mfcc.shape

((7442, 7), (7442, 22), (7442, 60))

In [46]:
df_fund.head()

,f0_mean,f0_median,f0_std,f0_0,f0_25,f0_75,f0_100
0,143.968106,148.970231,14.276620,118.920712,128.937031,156.013045,171.119005
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,209.558210,214.354693,14.447512,182.344498,196.564120,221.913894,235.109581
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_mfcc.isnull().values.sum()

0

In [47]:
df = pd.read_csv('/content/drive/MyDrive/LY Project/Dataframes/Dataset/merged_dataframe.csv')
print('The dataset has {} audio files'.format(df.shape[0]))
df.sample()

The dataset has 11970 audio files

,path,filename,dataset,duration,sample_rate,gender,age,emotion
1316,cremad/AudioWAV/1017_IEO_HAP_MD.wav,1017_IEO_HAP_MD,CREMA-D,1.835,16000,male,42,happy

In [48]:
df_crema = df[df['dataset'] == 'CREMA-D'].copy()

In [49]:
df_crema.shape

(7442, 8)

In [50]:
df_crema.head()

,path,filename,dataset,duration,sample_rate,gender,age,emotion
0,cremad/AudioWAV/1001_DFA_ANG_XX.wav,1001_DFA_ANG_XX,CREMA-D,2.276,16000,male,51,angry
1,cremad/AudioWAV/1001_DFA_DIS_XX.wav,1001_DFA_DIS_XX,CREMA-D,2.336,16000,male,51,disgust
2,cremad/AudioWAV/1001_DFA_FEA_XX.wav,1001_DFA_FEA_XX,CREMA-D,2.169,16000,male,51,fear
3,cremad/AudioWAV/1001_DFA_HAP_XX.wav,1001_DFA_HAP_XX,CREMA-D,1.869,16000,male,51,happy
4,cremad/AudioWAV/1001_DFA_NEU_XX.wav,1001_DFA_NEU_XX,CREMA-D,2.035,16000,male,51,neutral

In [51]:
import os

In [52]:
# saving the new cleaned files path in a variable
cleaned_files = sorted(filter(os.path.isfile, glob('/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/10*.wav')),key=os.path.getmtime)

In [53]:
len(cleaned_files)
print(cleaned_files[:100])

['/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_DFA_ANG_XX_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_DFA_DIS_XX_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_DFA_FEA_XX_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_DFA_HAP_XX_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_DFA_NEU_XX_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_DFA_SAD_XX_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_IEO_ANG_HI_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_IEO_ANG_LO_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_IEO_ANG_MD_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_IEO_DIS_HI_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_IEO_DIS_LO_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_IEO_DIS_MD_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_IEO_FEA_HI_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_IEO_FEA_LO_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_IEO_FEA_MD_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_IEO_HAP_HI_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_IEO_HAP_LO_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_IEO_HAP_MD_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_IEO_NEU_XX_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_IEO_SAD_HI_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_IEO_SAD_LO_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_IEO_SAD_MD_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_IOM_ANG_XX_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_IOM_DIS_XX_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_IOM_FEA_XX_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_IOM_HAP_XX_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_IOM_NEU_XX_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_IOM_SAD_XX_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_ITH_ANG_XX_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_ITH_DIS_XX_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_ITH_FEA_XX_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_ITH_HAP_XX_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_ITH_NEU_XX_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_ITH_SAD_XX_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_ITS_ANG_XX_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_ITS_DIS_XX_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_ITS_FEA_XX_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_ITS_HAP_XX_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_ITS_NEU_XX_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_ITS_SAD_XX_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_IWL_ANG_XX_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_IWL_DIS_XX_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_IWL_FEA_XX_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_IWL_HAP_XX_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_IWL_NEU_XX_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_IWL_SAD_XX_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_IWW_ANG_XX_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_IWW_DIS_XX_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_IWW_FEA_XX_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_IWW_HAP_XX_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_IWW_NEU_XX_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_IWW_SAD_XX_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_MTI_ANG_XX_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_MTI_DIS_XX_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_MTI_FEA_XX_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_MTI_HAP_XX_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_MTI_NEU_XX_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_MTI_SAD_XX_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_TAI_ANG_XX_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_TAI_DIS_XX_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_TAI_FEA_XX_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_TAI_HAP_XX_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_TAI_NEU_XX_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_TAI_SAD_XX_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_TIE_ANG_XX_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_TIE_DIS_XX_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_TIE_FEA_XX_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_TIE_HAP_XX_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_TIE_NEU_XX_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_TIE_SAD_XX_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_TSI_ANG_XX_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_TSI_DIS_XX_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_TSI_FEA_XX_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_TSI_HAP_XX_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_TSI_NEU_XX_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_TSI_SAD_XX_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_WSI_ANG_XX_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_WSI_DIS_XX_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_WSI_FEA_XX_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_WSI_HAP_XX_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_WSI_NEU_XX_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1001_WSI_SAD_XX_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1002_DFA_ANG_XX_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1002_DFA_DIS_XX_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1002_DFA_FEA_XX_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1002_DFA_HAP_XX_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1002_DFA_NEU_XX_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1002_DFA_SAD_XX_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1002_IEO_ANG_HI_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1002_IEO_ANG_LO_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1002_IEO_ANG_MD_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1002_IEO_DIS_HI_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1002_IEO_DIS_LO_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1002_IEO_DIS_MD_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1002_IEO_FEA_HI_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1002_IEO_FEA_LO_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1002_IEO_FEA_MD_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1002_IEO_HAP_HI_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1002_IEO_HAP_LO_cleaned.wav', '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1002_IEO_HAP_MD_cleaned.wav']

In [59]:
fnames = []

for fname in cleaned_files:
  p = fname.split('/')[-1].split('.')[0].split('_')
  temp = p.pop()
  s = '_'
  a = s.join(p)
  fnames.append(a)

# fname = [i.split('/')[-1].split('.')[0].split('_') for i in cleaned_files]
print(fnames[:100])

['1001_DFA_ANG_XX', '1001_DFA_DIS_XX', '1001_DFA_FEA_XX', '1001_DFA_HAP_XX', '1001_DFA_NEU_XX', '1001_DFA_SAD_XX', '1001_IEO_ANG_HI', '1001_IEO_ANG_LO', '1001_IEO_ANG_MD', '1001_IEO_DIS_HI', '1001_IEO_DIS_LO', '1001_IEO_DIS_MD', '1001_IEO_FEA_HI', '1001_IEO_FEA_LO', '1001_IEO_FEA_MD', '1001_IEO_HAP_HI', '1001_IEO_HAP_LO', '1001_IEO_HAP_MD', '1001_IEO_NEU_XX', '1001_IEO_SAD_HI', '1001_IEO_SAD_LO', '1001_IEO_SAD_MD', '1001_IOM_ANG_XX', '1001_IOM_DIS_XX', '1001_IOM_FEA_XX', '1001_IOM_HAP_XX', '1001_IOM_NEU_XX', '1001_IOM_SAD_XX', '1001_ITH_ANG_XX', '1001_ITH_DIS_XX', '1001_ITH_FEA_XX', '1001_ITH_HAP_XX', '1001_ITH_NEU_XX', '1001_ITH_SAD_XX', '1001_ITS_ANG_XX', '1001_ITS_DIS_XX', '1001_ITS_FEA_XX', '1001_ITS_HAP_XX', '1001_ITS_NEU_XX', '1001_ITS_SAD_XX', '1001_IWL_ANG_XX', '1001_IWL_DIS_XX', '1001_IWL_FEA_XX', '1001_IWL_HAP_XX', '1001_IWL_NEU_XX', '1001_IWL_SAD_XX', '1001_IWW_ANG_XX', '1001_IWW_DIS_XX', '1001_IWW_FEA_XX', '1001_IWW_HAP_XX', '1001_IWW_NEU_XX', '1001_IWW_SAD_XX', '1001_MTI_ANG_XX', '1001_MTI_DIS_XX', '1001_MTI_FEA_XX', '1001_MTI_HAP_XX', '1001_MTI_NEU_XX', '1001_MTI_SAD_XX', '1001_TAI_ANG_XX', '1001_TAI_DIS_XX', '1001_TAI_FEA_XX', '1001_TAI_HAP_XX', '1001_TAI_NEU_XX', '1001_TAI_SAD_XX', '1001_TIE_ANG_XX', '1001_TIE_DIS_XX', '1001_TIE_FEA_XX', '1001_TIE_HAP_XX', '1001_TIE_NEU_XX', '1001_TIE_SAD_XX', '1001_TSI_ANG_XX', '1001_TSI_DIS_XX', '1001_TSI_FEA_XX', '1001_TSI_HAP_XX', '1001_TSI_NEU_XX', '1001_TSI_SAD_XX', '1001_WSI_ANG_XX', '1001_WSI_DIS_XX', '1001_WSI_FEA_XX', '1001_WSI_HAP_XX', '1001_WSI_NEU_XX', '1001_WSI_SAD_XX', '1002_DFA_ANG_XX', '1002_DFA_DIS_XX', '1002_DFA_FEA_XX', '1002_DFA_HAP_XX', '1002_DFA_NEU_XX', '1002_DFA_SAD_XX', '1002_IEO_ANG_HI', '1002_IEO_ANG_LO', '1002_IEO_ANG_MD', '1002_IEO_DIS_HI', '1002_IEO_DIS_LO', '1002_IEO_DIS_MD', '1002_IEO_FEA_HI', '1002_IEO_FEA_LO', '1002_IEO_FEA_MD', '1002_IEO_HAP_HI', '1002_IEO_HAP_LO', '1002_IEO_HAP_MD']

In [61]:
len(fnames)

7442

In [62]:
df_all = pd.concat([df_fund, df_misc, df_mfcc], axis=1)
df_all.head()

,f0_mean,f0_median,f0_std,f0_0,f0_25,f0_75,f0_100,zcr_mean,zcr_var,spectral_centroid_mean,...,mfcc21_var,mfcc22_var,mfcc23_var,mfcc24_var,mfcc25_var,mfcc26_var,mfcc27_var,mfcc28_var,mfcc29_var,mfcc30_var
0,143.968106,148.970231,14.276620,118.920712,128.937031,156.013045,171.119005,0.139486,0.003016,2580.862074,...,12.067534,51.701720,40.290375,24.630281,28.642622,15.932327,20.521797,15.425456,26.070824,19.798725
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.145508,0.003464,2662.940576,...,37.610740,58.615696,36.562880,28.327286,49.040176,13.156686,16.329580,16.562145,12.162917,24.490680
2,209.558210,214.354693,14.447512,182.344498,196.564120,221.913894,235.109581,0.136850,0.002800,2664.678926,...,23.228825,18.514380,15.132082,47.379417,86.794395,85.855760,139.807360,34.445213,187.592910,218.944240
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.123215,0.002535,2563.258338,...,48.368275,35.085728,19.069424,31.322933,27.873602,31.837790,82.312840,79.608795,94.755120,84.363434
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.111637,0.001839,2393.284424,...,33.261497,20.141462,18.237373,16.503407,19.326670,25.585768,39.639137,23.999023,22.622560,15.125541

In [ ]:
# df_all.rename(columns = {'path':'filename'}, inplace = True)

In [66]:
df_all['filename'] = fnames

In [67]:
df_all.head()

,f0_mean,f0_median,f0_std,f0_0,f0_25,f0_75,f0_100,zcr_mean,zcr_var,spectral_centroid_mean,...,mfcc22_var,mfcc23_var,mfcc24_var,mfcc25_var,mfcc26_var,mfcc27_var,mfcc28_var,mfcc29_var,mfcc30_var,filename
0,143.968106,148.970231,14.276620,118.920712,128.937031,156.013045,171.119005,0.139486,0.003016,2580.862074,...,51.701720,40.290375,24.630281,28.642622,15.932327,20.521797,15.425456,26.070824,19.798725,1001_DFA_ANG_XX
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.145508,0.003464,2662.940576,...,58.615696,36.562880,28.327286,49.040176,13.156686,16.329580,16.562145,12.162917,24.490680,1001_DFA_DIS_XX
2,209.558210,214.354693,14.447512,182.344498,196.564120,221.913894,235.109581,0.136850,0.002800,2664.678926,...,18.514380,15.132082,47.379417,86.794395,85.855760,139.807360,34.445213,187.592910,218.944240,1001_DFA_FEA_XX
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.123215,0.002535,2563.258338,...,35.085728,19.069424,31.322933,27.873602,31.837790,82.312840,79.608795,94.755120,84.363434,1001_DFA_HAP_XX
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.111637,0.001839,2393.284424,...,20.141462,18.237373,16.503407,19.326670,25.585768,39.639137,23.999023,22.622560,15.125541,1001_DFA_NEU_XX

In [68]:
df_final_crema = pd.merge(df, df_all, how = 'inner', on = 'filename')

In [74]:
df_final_crema.sample(2)

,path,filename,dataset,duration,sample_rate,gender,age,emotion,f0_mean,f0_median,...,mfcc21_var,mfcc22_var,mfcc23_var,mfcc24_var,mfcc25_var,mfcc26_var,mfcc27_var,mfcc28_var,mfcc29_var,mfcc30_var
3277,cremad/AudioWAV/1041_IEO_HAP_LO.wav,1041_IEO_HAP_LO,CREMA-D,2.102,16000,male,42,happy,119.320822,120.999409,...,14.43374,13.534598,15.557288,10.675119,9.358923,16.622171,11.085197,10.708691,12.225942,15.055571
7414,cremad/AudioWAV/1091_MTI_FEA_XX.wav,1091_MTI_FEA_XX,CREMA-D,2.669,16000,female,29,fear,245.200483,244.105706,...,109.24627,64.036490,294.747300,232.027910,263.945560,270.971200,225.274700,175.005940,81.183130,96.004830

Warning: Total number of columns (97) exceeds max_columns (20) limiting to first (20) columns.

In [73]:
df_final_crema.to_csv('/content/drive/MyDrive/LY Project/Dataframes/Features/Crema-D/DF_FINAL_CREMA.csv', index = False)

In [80]:
f_path = '/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/' + df_final_crema['filename'][7414] + '_cleaned.wav'
f_path

'/content/drive/MyDrive/LY Project/Cleaned Datasets/cleaned_samples_tess_savee_ravdess_crema/1091_MTI_FEA_XX_cleaned.wav'

In [82]:
get_f0(f_path)

In [ ]:
zcr_mean, zcr_var, spectral_centroid_mean, spectral_centroid_var, rms_mean, rms_var, chroma_stft_mean, chroma_stft_var = [], [], [], [], [], [], [], []
rolloff_mean, rolloff_var, spectral_bandwidth_mean, spectral_bandwidth_var, harmony_mean, harmony_var, chroma_cqt_mean, chroma_cqt_var = [], [], [], [], [], [], [], []
spectral_contrast_mean, spectral_contrast_var, spectral_flatness_mean, spectral_flatness_var, chroma_cens_mean, chroma_cens_var = [], [], [], [], [], []

In [81]:
f0_mean, f0_median, f0_std, f0_0, f0_25, f0_75, f0_100 = [], [], [], [], [], [], []

# Function to extract f0 values
def get_f0(file):
    # load audio file:
    y, sr = librosa.load(file, sr=16000)
    
    # Extract fundamental frequency using a probabilistic approach
    f_zero, _, _ = librosa.pyin(y, sr=sr, fmin=50, fmax=1500, frame_length=1024)

    f0_mean.append(np.nanmean(f_zero))             # f0 mean
    f0_median.append(np.nanmedian(f_zero))         # f0 median
    f0_std.append(np.nanstd(f_zero))               # f0 standar deviation
    f0_0.append(np.nanpercentile(f_zero, 0))       # f0 min
    f0_25.append(np.nanpercentile(f_zero, 25))     # f0 25%-percentile value
    f0_75.append(np.nanpercentile(f_zero, 75))     # f0 75%-percentile value
    f0_100.append(np.nanpercentile(f_zero, 100))   # f0 max

In [ ]:
print('h1')

In [ ]:
%%time

# declare variables where to store the extracted feaures
zcr_mean, zcr_var, spectral_centroid_mean, spectral_centroid_var, rms_mean, rms_var, chroma_stft_mean, chroma_stft_var = [], [], [], [], [], [], [], []
rolloff_mean, rolloff_var, spectral_bandwidth_mean, spectral_bandwidth_var, harmony_mean, harmony_var, chroma_cqt_mean, chroma_cqt_var = [], [], [], [], [], [], [], []
spectral_contrast_mean, spectral_contrast_var, spectral_flatness_mean, spectral_flatness_var, chroma_cens_mean, chroma_cens_var = [], [], [], [], [], []

# extract features
for file in (cleaned_files):
    # load audio file:
    y, sr = librosa.load(file, sr=16000)
    
    # Zero crossing rate
    zcr_mean.append(np.mean(librosa.feature.zero_crossing_rate(y)))
    zcr_var.append(np.var(librosa.feature.zero_crossing_rate(y)))
    
    # Spectral centroid
    spectral_centroid_mean.append(np.mean(librosa.feature.spectral_centroid(y)))
    spectral_centroid_var.append(np.var(librosa.feature.spectral_centroid(y)))
    
    # Spectral contrast
    spectral_contrast_mean.append(np.mean(librosa.feature.spectral_contrast(y)))
    spectral_contrast_var.append(np.var(librosa.feature.spectral_contrast(y)))
    
    # Spectral flatness
    spectral_flatness_mean.append(np.mean(librosa.feature.spectral_flatness(y)))
    spectral_flatness_var.append(np.var(librosa.feature.spectral_flatness(y)))
    
    # Rms mean and variance
    rms_mean.append(np.mean(librosa.feature.rms(y=y)))               
    rms_var.append(np.var(librosa.feature.rms(y=y)))
    
    # Chroma mean and variance
    chroma_stft_mean.append(np.mean(librosa.feature.chroma_stft(y, sr)))                   
    chroma_stft_var.append(np.var(librosa.feature.chroma_stft(y, sr)))
    
    #Chroma cqt mean and variance
    chroma_cqt_mean.append(np.mean(librosa.feature.chroma_cqt(y, sr)))                   
    chroma_cqt_var.append(np.var(librosa.feature.chroma_cqt(y, sr)))
    
    #Chroma cens mean and variance
    chroma_cens_mean.append(np.mean(librosa.feature.chroma_cens(y, sr)))                   
    chroma_cens_var.append(np.var(librosa.feature.chroma_cens(y, sr)))
    
    # Rolloff mean and variance
    rolloff_mean.append(np.mean(librosa.feature.spectral_rolloff(y,sr)))
    rolloff_var.append(np.var(librosa.feature.spectral_rolloff(y,sr)))
    
    # Spectral bandwidth mean and variance
    spectral_bandwidth_mean.append(np.mean(librosa.feature.spectral_bandwidth(y,sr)))
    spectral_bandwidth_var.append(np.var(librosa.feature.spectral_bandwidth(y,sr)))
    
    # Harmony mean and variance
    harmony_mean.append(np.mean(librosa.effects.harmonic(y)))
    harmony_var.append(np.var(librosa.effects.harmonic(y)))

In [ ]:
# add new features to a new dataframe
df_features = pd.DataFrame()
df_features['zcr_mean'] = zcr_mean
df_features['zcr_var'] = zcr_var
df_features['spectral_centroid_mean'] = spectral_centroid_mean
df_features['spectral_centroid_var'] = spectral_centroid_var
df_features['spectral_contrast_mean'] = spectral_contrast_mean
df_features['spectral_contrast_var'] = spectral_contrast_var
df_features['spectral_flatness_mean'] = spectral_flatness_mean
df_features['spectral_flatness_var'] = spectral_flatness_var
df_features['rms_mean'] = rms_mean
df_features['rms_var'] = rms_var
df_features['chroma_stft_mean'] = chroma_stft_mean
df_features['chroma_stft_var'] = chroma_stft_var
df_features['chroma_cqt_mean'] = chroma_cqt_mean
df_features['chroma_cqt_var'] = chroma_cqt_var
df_features['chroma_cens_mean'] = chroma_cens_mean
df_features['chroma_cens_var'] = chroma_cens_var
df_features['spectral_bandwidth_mean'] = spectral_bandwidth_mean
df_features['spectral_bandwidth_var'] = spectral_bandwidth_var
df_features['rolloff_mean'] = rolloff_mean
df_features['rolloff_var'] = rolloff_var
df_features['harmony_mean'] = harmony_mean
df_features['harmony_var'] = harmony_var
# Check a random row
df_features.sample()

,zcr_mean,zcr_var,spectral_centroid_mean,spectral_centroid_var,spectral_contrast_mean,spectral_contrast_var,spectral_flatness_mean,spectral_flatness_var,rms_mean,rms_var,chroma_stft_mean,chroma_stft_var,chroma_cqt_mean,chroma_cqt_var,chroma_cens_mean,chroma_cens_var,spectral_bandwidth_mean,spectral_bandwidth_var,rolloff_mean,rolloff_var,harmony_mean,harmony_var
2,0.203249,0.028253,3286.975787,2.798112e+06,24.775197,169.624925,0.026869,0.001662,0.017903,0.000084,0.291912,0.102972,0.392072,0.092326,0.265163,0.013022,1652.695748,181814.9458,4143.382353,3.138676e+06,-5.880196e-08,0.000111

In [ ]:
df_features.to_csv('/content/drive/MyDrive/LY Project/ravdess_features.csv')

### <a id='2_b3'>MFCCs</a>

In [ ]:
def extract_mfcc(file):
    
    mfcc_mean, mfcc_var = [], []
    
    # load audio file:
    y, sr = librosa.load(file, sr=16000)
    
    # get 20 mean values
    mfcc_mean.append(np.mean(librosa.feature.mfcc(y=y, sr=sr, fmin=50, n_mfcc=30).T, axis=0))
    
    # get 20 variance values
    mfcc_var.append(np.var(librosa.feature.mfcc(y=y, sr=sr, fmin=50, n_mfcc=30).T, axis=0))
    
    return np.hstack((mfcc_mean, mfcc_var))[0]

In [ ]:
# function to extract mean and variance of Mel-Frequency Cepstrum Components (MFCCs)
def extract_mfcc(file):
    
    mfcc_mean, mfcc_var = [], []
    
    # load audio file:
    y, sr = librosa.load(file, sr=16000)
    
    # get 20 mean values
    mfcc_mean.append(np.mean(librosa.feature.mfcc(y=y, sr=sr, fmin=50, n_mfcc=30).T, axis=0))
    
    # get 20 variance values
    mfcc_var.append(np.var(librosa.feature.mfcc(y=y, sr=sr, fmin=50, n_mfcc=30).T, axis=0))
    
    return np.hstack((mfcc_mean, mfcc_var))[0]

# apply function above to all files and store results in a list
extracted_mfcc = []

for file in cleaned_files:
    extracted_mfcc.append(extract_mfcc(file))

# create column names for a dataframe
name_mfcc_mean, name_mfcc_var = [], []

for i in range(0, 30):
    name_mfcc_mean.append('mfcc'+str(i+1)+'_mean')   # mfcc1_mean, mfcc2_mean, ...
    name_mfcc_var.append('mfcc'+str(i+1)+'_var')     # mfcc1_var, mfcc2_var, ...

name_mfcc = name_mfcc_mean + name_mfcc_var           # concatenate mfcc mean and variance names

# finally put all mfcc values in a dataframe
df_mfcc = pd.DataFrame(extracted_mfcc, columns = name_mfcc)
df_mfcc.sample()      # print one sample

,mfcc1_mean,mfcc2_mean,mfcc3_mean,mfcc4_mean,mfcc5_mean,mfcc6_mean,mfcc7_mean,mfcc8_mean,mfcc9_mean,mfcc10_mean,...,mfcc21_var,mfcc22_var,mfcc23_var,mfcc24_var,mfcc25_var,mfcc26_var,mfcc27_var,mfcc28_var,mfcc29_var,mfcc30_var
219,-376.568237,80.555634,-13.57391,11.430367,-7.41145,-3.916821,-18.955059,-11.125784,-34.169258,7.272757,...,151.700882,250.190964,113.27565,178.498749,407.541016,543.904114,493.671326,322.549255,219.207306,160.651962

In [ ]:
df_mfcc.to_csv('/content/drive/MyDrive/LY Project/ravdess_mfcc_features.csv')

## <a id='3_a'>Merge and export all the extracted features<a>

As it turned out, some operations used to take a long time to be done.
    
Finally, I can merge all the data into one dataframe and export it to perform the EDA. I can also remove the `sample_rate` column, now that the samples frequency is the same for each cleaned audio file (16000 Hz).

In [ ]:
# Merge dataframes and print few samples
data_features = pd.concat([df, df_f0, df_features, df_mfcc], axis=1)

# Remove `sample_rate` column
data_features = data_features.drop(['sample_rate'], axis=1)

# Check one random row
data_features.sample()

,path,filename,dataset,duration,gender,age,emotion,f0_mean,f0_median,f0_std,...,mfcc21_var,mfcc22_var,mfcc23_var,mfcc24_var,mfcc25_var,mfcc26_var,mfcc27_var,mfcc28_var,mfcc29_var,mfcc30_var
10603,toronto-emotional-speech-set-tess/TESS Toronto...,YAF_angry/YAF_dodge_angry,TESS,2.381,female,26,angry,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# write csv
data_features.to_csv('/content/drive/MyDrive/LY Project/ravdess_data_features.csv', index=False)

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/LY Project/Dataframes/Features/Ravdess/ravdess_data_features.csv')

In [ ]:
df[df['dataset'] == 'RAVDESS']

,path,filename,dataset,duration,gender,age,emotion,f0_mean,f0_median,f0_std,...,mfcc21_var,mfcc22_var,mfcc23_var,mfcc24_var,mfcc25_var,mfcc26_var,mfcc27_var,mfcc28_var,mfcc29_var,mfcc30_var
7442,ravdess-emotional-speech-audio/Actor_01/03-01-...,03-01-01-01-01-01-01,RAVDESS,3.303,male,26,neutral,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7443,ravdess-emotional-speech-audio/Actor_01/03-01-...,03-01-01-01-01-02-01,RAVDESS,3.337,male,26,neutral,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7444,ravdess-emotional-speech-audio/Actor_01/03-01-...,03-01-01-01-02-01-01,RAVDESS,3.270,male,26,neutral,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7445,ravdess-emotional-speech-audio/Actor_01/03-01-...,03-01-01-01-02-02-01,RAVDESS,3.170,male,26,neutral,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7446,ravdess-emotional-speech-audio/Actor_01/03-01-...,03-01-03-01-01-01-01,RAVDESS,3.470,male,26,happy,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8685,ravdess-emotional-speech-audio/Actor_24/03-01-...,03-01-08-01-02-02-24,RAVDESS,3.403,female,26,surprise,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8686,ravdess-emotional-speech-audio/Actor_24/03-01-...,03-01-08-02-01-01-24,RAVDESS,3.937,female,26,surprise,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8687,ravdess-emotional-speech-audio/Actor_24/03-01-...,03-01-08-02-01-02-24,RAVDESS,3.971,female,26,surprise,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8688,ravdess-emotional-speech-audio/Actor_24/03-01-...,03-01-08-02-02-01-24,RAVDESS,3.670,female,26,surprise,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8689,ravdess-emotional-speech-audio/Actor_24/03-01-...,03-01-08-02-02-02-24,RAVDESS,3.637,female,26,surprise,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<br>[Back to top](#top2)